### ISSUE TITLE
ขอคำปรึกษาเรื่อง Type Classification ของแบบตัว KoHo ค่ะ 

### ISSUE THREAD

**Issue by siringunkloy** [cadsondemak/Koho#2]
จากต้นฉบับ ถ้าจัดการแบบ (โดยเฉพาะตัวละติน) ให้อยู่ในแนวทางของ Neo-Humanist Sans (FF Meta, FF Dax) จะสอดคล้องกับเจตนาตั้งต้นของแบบหรือไม่คะ  

ส่วนตัวไทย คิดว่าถ้า Latin เป็นไปตามนี้ คงจัดการในแนวทางของกลุ่ม Humanist (ex. โมโนไทป์, สารบรรณ) ค่ะ
![koho original design](https://user-images.githubusercontent.com/35678481/36776746-8555d1ea-1c99-11e8-907f-75171a703618.jpg)
![koho original design2](https://user-images.githubusercontent.com/35678481/36777128-dc59f2e0-1c9a-11e8-9fb0-2df10b7a64d3.jpg)

**Comment by suppakit-** [comment]
ในความเห็นของผม คิดว่าในส่วนของหัวตัวอักษรไทยมันเอียงไปเอียงมา ทำให้ตัวอักษรทั้งชุดดูโย้เย้ครับ ถ้าเป็นได้คิดว่าปรับหัวให้อยู่ในระบบที่เป็นระเบียบกว่านี้น่าจะดีกว่าครับ รอความเห็นท่านอื่นนะครับ :)

**Comment by AnuthinWongsunkakon** [comment]
พิมพ์ใหญ่ กว้างได้มากกว่านี้ ตอนนี้พิมพ์ใหญ่ดูแคบสูง แบบไม่ต้องเปลี่ยนหรอกครับ เอาเป็นว่าปรับให้สัดส่วนถูก ไม่ย้วยก็พอนะ อันไหนที่ต้องขยับเพื่อให้เป็นละตินที่น่าเชื่อขึ้นก็ควรทำ เพราะว่าต้องปล่อยให้ดูนาอีฟไว้ด้วยในดีกรีนึงนะครับ ไม่งั้นเจตนามันจะหาย

ตอยที่เช่คือ ผมเห็นด้วยครับที่มันทำให้โย้เย้ไปมา กลับมองว่าควรเก็บความไร้แบบแผนของโพซิชั่นหัวไว้ แต่มาหาทางออกว่าจะทำยังไงให้มันไม่โย้เย้ดีกว่า งงไหมเอ่ย? ลองไปอ่านที่ผมคอมเม้นท์ใน issue ถัดไป

ต้องจัดการเรื่องความหนาบางที่ไม่รู้ว่าตัดสินให้ได้รางวัลมาได้ไง ทำไมไม่มีการรัไฟน์แบบก่อนที่จะปล่อยพับลิค มันอยู่ในวิสัยที่ซ่อมได้ เป็นเรื่องพื้นฐาน สงสัยตาบอดกันทั้งแผงคนตรวจ ไม่อยากโทษแบบ เพราะต้องการคอมเม้นท์ที่ไม่ได้เกิดขึ้น เรื่องแบบนี้ต้องโทษคนตรวจตรวจเรื่อง principal ไม่ได้

**Comment by siringunkloy** [comment]
ขอบคุณค่ะ จะลองจัดการในภาพรวมตามคำแนะนำจากทุกคนดูค่ะ  ส่วนอื่นๆที่เป็นรายละเอียดจะนำมาทยอยเปิดหัวข้อเจาะเป็นประเด็นๆ ไปหลังจากนี้คะ

**Comment by AnuthinWongsunkakon** [comment]
ขอ screen capture ของตัวละตินหน่อยครับ ผมคิดว่าคงต้องดูภาพรวมตัวละตินเพื่อคอมเม้นท์ไปทีเดียว

**Comment by siringunkloy** [comment]
กำลังจัดทำพอดีค่ะ สักครู่นะคะ :)
