### ISSUE TITLE
Koho - ขอคำปรึกษาเรื่องระบบการหันหัวของตัวภาษาไทยค่ะ (Loop axis system)

### ISSUE THREAD

**Issue by siringunkloy** [cadsondemak/Koho#3]
ระบบหันหัวทั้งหมดที่มีตอนนี้ค่ะ อยากขอคำปรึกษาว่าควรเก็บ หรือไม่ควรเก็บการหันแบบไหนค่ะ 
![koho original design](https://user-images.githubusercontent.com/35678481/36786262-66bfc942-1cb8-11e8-9800-b8870e35d119.jpg)
![koho original design2](https://user-images.githubusercontent.com/35678481/36958562-5254295c-206f-11e8-94bb-9c6127ace955.jpg)
![koho original design3](https://user-images.githubusercontent.com/35678481/36958570-5fdc0162-206f-11e8-90fc-821a6eef7c01.jpg)
![koho original design4](https://user-images.githubusercontent.com/35678481/36958575-7210a20c-206f-11e8-9891-4952b3b7e128.jpg)

**Comment by AnuthinWongsunkakon** [comment]
ผมมองว่า ความไร้ระบบของหัวเป็นบุคลิกที่น่าเก็บไว้นะครับ หากแต่ว่าน่าจะมีปัญหาตรงเรื่องของขนาดและอาจจะต้องบริหารจัดการการเอียงไปเอียงมาปัดไปปัดมา ความหนาและอื่นๆ เพราะถ้าเราเอามาเป็นหัวแบบเดียวหรือในะบบที่เป็นสองแบบ (หรือที่มีทางเลือกซ้ำๆสองสามกรณี) อาจจะทำให้บุคลิกตรงนี้หายไป ความหละหลวมของระบบมันกลายไปเป็นแคแรคเตอร์ไปแล้ว ถ้าทำให้เป็นระบบจะทำให้แข็งไปหมด 

ฉะนั้นผมว่าเราควรมาหาวิธีจัดการกับความหนา ขนาด และองศาต่างๆให้มีโลจิกบางประการที่อธิบายได้(กว่านี้)น่าจะดีกว่า

**Comment by siringunkloy** [comment]
ขอบคุณค่ะอาจารย์

**Comment by AnuthinWongsunkakon** [comment]
ฝากไล่ดูด้วยครับว่า node มันอยู่ถูกที่ไหม ยังไงใช้ RMX Harmonizer ช่วยอีกทีก็ได้นะครับ แต่ก็ควรจะไล่เช็คอีกทีนะครับ เพราะสำหรับภาษาไทยมัยอาจจะอ่านเจตนาเราไม่ออก เดี๋ยวปรับออโต้แล้วผิด
