### ISSUE TITLE
แบบตัวละตินที่ปรับ proportion และรายละเอียดแล้วค่ะ

### ISSUE THREAD

**Issue by siringunkloy** [cadsondemak/Koho#4]
![koho original](https://user-images.githubusercontent.com/35678481/37382427-6328836a-2775-11e8-97d1-cf72f83f4498.png)
![koho](https://user-images.githubusercontent.com/35678481/37382434-6826db78-2775-11e8-80db-43acf11887e8.png)

![mediavilla](https://user-images.githubusercontent.com/35678481/37382373-1fe828a8-2775-11e8-9222-6a7b2f2682bd.jpg)
![84963](https://user-images.githubusercontent.com/35678481/37382379-2919ca58-2775-11e8-8e63-bd3aa31815c6.png)

- ปรับ proportion ตัวละตินมาตามคำแนะนำค่ะ
- terminal ส่วนหลังคาในภาพรวม อาทิในตัว C,G,S, J และ a, c, e,s จะเห็นว่าของเดิมมีผสมทั้ง แบบตั้งฉาก แบบแหงนขึ้น30องศา แบบตัดในแนวระนาบ จากการมองภาพรวม เลยหาค่ากลางใหม่ ตอนนี้ใช้ระบบแหงนขึ้นเล้กน้อยทั้งหมดค่ะ [เข้าใจว่าในตัว a เล็กของเดิม เจตนาคงอยากให้มี linkage กลับไปที่หลังคาตัวไทยค่ะ (ล, ส)  แต่พบว่าไม่ได้แชร์ระบบเดียวกันกับตัวใดภายในชุดภาษาอังกฤษเลย เบื้องต้นจึงลองปรับออกค่ะ ภาพรวม texture เป็นที่น่าพอใจค่ะ]
- ส่วนเรื่องทิศทางการสะบัดของ terminal ที่เป็น flair ยังไม่ค่อยแน่ใจเรื่องทิศทางการหันปลาย (b, d และ p, q)
เท่าที่หาข้อมูลมาบ้าง จึงปรับโดยเอาของเดิมตั้งและดูตามแบบการคัด calligraphy (Foundational Roundhand) กับตัวฟอนต์ลายมือปัจจุบัน (ex.Cronos, Rumba)  แต่เบื้องต้นไม่ได้ใส่ตามทั้งหมด เพราะจากแบบจะต้องมีปลายจบในแนวระนาบคลุกอยู่ด้วย จะพยายามจัดการให้ในหนึ่งอักษรมีทั้งปลายสะบัดและปลายตัดระนาบค่ะ เช่น l  
- ปิดช่องตัว B
- ปรับขาล่างตัว K,R,k  
อื่นๆ ที่อยากทราบคือ อย่างตัว V, W จำเป็นของมี Apex อยู่ในแนวทางเดียวกันไหมคะ 
ไฟล์ pdf ค่ะ
[KoHo_original.pdf](https://github.com/cadsondemak/Koho/files/1809465/KoHo_original.pdf)
[KoHo.glyphs.pdf](https://github.com/cadsondemak/Koho/files/1809503/KoHo.glyphs.pdf)

**Comment by siringunkloy** [comment]
- ตัว J ที่ปรับมาใหม่กว้างเกินไปไหมคะ หรือควรเก็บให้แคบอย่างเดิม

**Comment by AnuthinWongsunkakon** [comment]
I am glad to see this. It makes lot more sense to me. Especially the Latin is much better than the original. I would recommend you to use just a regular circle dot for i and j. The original just does not make any sense why do they have to be oval.

The small curve on M N W and w are quite uncomfortable to me. I wish we could terminate this idea. —Or— If you would like to leave something like the lower right corner of N and apply to M and W, this might do some good for keeping the original design.
 
G without spur is ok. I see that you try to keep it the to the original. I wish you could make the chin of G less curve. It is too soft and too round right now. 

The tail of g and y is too square as well. It did not compliment to the rest of the rounded shape.

The lower left corner of Z z should be tighter curve than this. This same tight curve at the sharp corners like this should be applied to related shape in the set.

**Comment by siringunkloy** [comment]
Thank you! I'll keep you updated.

**Comment by AnuthinWongsunkakon** [comment]
@siringunkloy Please try to fix them accordingly. You will probably fix other related things as well.
