### ISSUE TITLE
*Noted on CEDI SIGN (U+20B5)

### ISSUE THREAD

**Issue by siringunkloy** [cadsondemak/Koho#5]
I'm wondering that which one is the correct slash for CEDI SIGN (U+20B5) OR can use both? :) 
![screen shot 2018-03-20 at 00 05 18](https://user-images.githubusercontent.com/35678481/37610632-b754863a-2bd2-11e8-9ae0-e452292319fa.png)
Here are some references I got. 
http://graphemica.com/%E2%82%B5
http://www.fileformat.info/info/unicode/char/20b5/index.htm

**Comment by AnuthinWongsunkakon** [comment]
I believe you can use either one but have to make sure that the size is closer to Capital C just like the normal currency sign should be. Do not get confused with ¢ (cent). The question is if in this set your $ ฿ are all straight line then most likely you should go with a straight bar not the diagonal. Does it make any sense?
